spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: taskuser
    password: taskpass
  jpa:
    hibernate:
      ddl-auto: update   # OK for development; use 'validate' in prod
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  mail:
    host: SMTP_HOST_HERE
    port: 587
    username: SMTP_USER_HERE
    password: SMTP_PASS_HERE
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true

jwt:
  secret: "123456789abcdefghijklmnopqrstuvwxyz123456789abcdefghijklmnopqrstuvwxyz"
  expirationMinutes: 120